### ISSUE TITLE
Add tag in masterclass cards

### ISSUE THREAD

**Issue by aaryanporwal** [canonical/masterclasses.canonical.com#16]
Currently, we don't have tag displayed on the masterclass card. We already fetch cards from the spreadsheet.

Just like in the below screenshot, we need to add the corresponding tag of the video, below the "Duration" field.

![masterclass-ss](https://github.com/canonical/masterclasses.canonical.com/assets/54525904/c84a51db-b0a5-4154-a54b-f5dba95059c5)

**Comment by edlerd** [comment]
Finished as part of https://github.com/canonical/masterclasses.canonical.com/pull/21
