### ISSUE TITLE
Replace reset button with two way interactive filters

### ISSUE THREAD

**Issue by aaryanporwal** [canonical/masterclasses.canonical.com#24]
When a filter is selected, the "Reset" option looks like a filter even though technically it's not. 

Filter elements should have two-way interactions. At the moment when the user selects a filter, they can't un-select by interacting with the same element. That is very unnatural.

**Comment by edlerd** [comment]
For clearing the tags, I think we should use the https://vanillaframework.io/docs/patterns/chip#chip-with-dismiss
So if a tag is active, it becomes green and gets a small x to clear it.
