### ISSUE TITLE
Getting HTTP 500

### ISSUE THREAD

**Issue by dimaqq** [canonical/masterclasses.canonical.com#51]
![Screenshot 2024-06-14 at 11 30 20](https://github.com/canonical/masterclasses.canonical.com/assets/662249/7fdaf092-9c54-49da-a210-6665df931bfa)

**Comment by dimaqq** [comment]
The above is the logged in view, as I was logged in previously

For logged out users, the login page is shown, as expected.

**Comment by aaryanporwal** [comment]
Thanks @dimaqq for reporting this. Currently investigating with the IS team.

**Comment by aaryanporwal** [comment]
Resolved. the site is back online.
