### ISSUE TITLE
404 from https://masterclasses.canonical.com/lxd-profiles-/-cloud-init-to-quickly-setup-dev-environments-class-1017 

### ISSUE THREAD

**Issue by TheRealFalcon** [canonical/masterclasses.canonical.com#59]
There is a link to https://masterclasses.canonical.com/lxd-profiles-/-cloud-init-to-quickly-setup-dev-environments-class-1017 from https://masterclasses.canonical.com/ , but the page does not exist.

**Comment by aaryanporwal** [comment]
Hey @TheRealFalcon thanks for filing an issue. The page is fixed for now, can you take a look?
The new URL is: https://masterclasses.canonical.com/lxd-profiles-%7C-cloud-init-to-quickly-setup-dev-environments-class-1017

**Comment by aaryanporwal** [comment]
The slugification broke the URL. The slugify function needs to be updated.

**Comment by TheRealFalcon** [comment]
LGTM, thanks! Feel free to close this unless you're using it as your slugify issue.
